### ISSUE TITLE
chrome,firefox 切换目录报错没有反应

### ISSUE THREAD

**Issue by GengShengJia** [MrWeilian/iceWebGL#1]
![image](https://github.com/MrWeilian/iceWebGL/assets/61140247/b9dc2c02-bad0-43aa-b6bb-e759989cbe2b)
如题

**Comment by MrWeilian** [comment]
刷新下还不行吗？我看好像没问题

**Comment by GengShengJia** [comment]
> 刷新下还不行吗？我看好像没问题

刷新后是可以 继续切换问题还是会出现 :(

**Comment by MrWeilian** [comment]
方便提供下录屏吗 我这边没复现出来

**Comment by GengShengJia** [comment]
链接: https://pan.baidu.com/s/1aqbToXTek2vYV6Z1HI_U5Q 提取码: u1ik

**Comment by MrWeilian** [comment]
😂浏览器什么版本的呀
![20230720-154738](https://github.com/MrWeilian/iceWebGL/assets/30046649/ec259cfe-d1b3-426d-8445-56a4c1f5b9fa)

**Comment by GengShengJia** [comment]
> 😂浏览器什么版本的呀 ![20230720-154738](https://user-images.githubusercontent.com/30046649/254812080-ec259cfe-d1b3-426d-8445-56a4c1f5b9fa.gif)

都是最新的版本
